#ifndef POKEHEARTGOLD_POKEDEX_LANGUAGE_H
#define POKEHEARTGOLD_POKEDEX_LANGUAGE_H

#define MAX_CAUGHT_LANGUAGES 6

int LanguageToDexFlag(u32 language);
u8 DexFlagToLanguage(int flag);

#endif //POKEHEARTGOLD_POKEDEX_LANGUAGE_H
